modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/JasdewStarfield/BRNTalk/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/JasdewStarfield/BRNTalk"
logoFile = "brntalk.png"
credits = "嘉轩, who has created all the texures for this mod"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "cloth_config"
mandatory = false
versionRange = "${cloth_config_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "ftblibrary"
mandatory = false
versionRange = "${ftblibrary_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "jei"
mandatory = false
versionRange = "${jei_version_range}"
ordering = "NONE"
side = "CLIENT"
